### ISSUE TITLE
[question]: Why not Parquet.Net

### ISSUE THREAD

**Issue by aloneguid** [bertt/geoparquet#6]
Hi there. I appreciate your awesome work on geoparquet. Just so you know - I'm one of the creators of Parquet.Net and I saw that you used it before but then changed. Can I ask why? I'm curious about geoparquet and how it works internally.

**Comment by bertt** [comment]
Hi Ivan, Yes correct I switched from Parquet.Net to ParquetSharp because of some limitations I encountered... Can't remember the details now should have written them down of course :-) Well it started just as a test of another Parquet library. 

Thinking about it maybe it had something to do with reading/writing Apache Arrow geometries, somehow reading worked with ParquetSharp but writing not (yet).

For reference this was the change needed to switch libraries:

https://github.com/bertt/geoparquet/commit/444955e3871bcd4e80571dae278fdd485095fcbb
